#!/bin/sh
ldconfig -vNX $(echo $LD_LIBRARY_PATH | sed 's/:/ /g') 2>/dev/null |
#/usr/lib32:
#   	libstdc++.so.6 -> libstdc++.so.6.0.26
#	    libgcc_s.so.1 -> libgcc_s.so.1
gawk -v p=$1 'match($0, /^(\S*):/, m)           { header=m[1] }    \
              match($1, "^lib") && match($1, p) { print header "/" $1}'
#/usr/lib32/libgcc_s.so.1
